"use client";

import { Candidate, EducationStatus, LanguageLevel, ProficiencyLevel } from "../lib/types";
import { Card, Field, Section, TextArea } from "./ui";

const levels: ProficiencyLevel[] = ["basic", "intermediate", "advanced", "expert"];
const languageLevels: LanguageLevel[] = ["basic", "intermediate", "advanced", "fluent", "native"];

export function CandidateForm({ candidate, setCandidate }: { candidate: Candidate; setCandidate: (candidate: Candidate) => void }) {
  const update = (path: string[], value: string) => {
    const next = structuredClone(candidate) as Candidate;
    let current: any = next;
    path.slice(0, -1).forEach(key => { current = current[key]; });
    current[path[path.length - 1]] = value;
    setCandidate(next);
  };
  const addExperience = () => setCandidate({ ...candidate, experiences: [...candidate.experiences, { company: "", role: "", start_date: "", end_date: null, activities: [], achievements: [] }] });
  const addEducation = () => setCandidate({ ...candidate, education: [...candidate.education, { institution: "", course: "", status: "completed", start_date: null, end_date: null }] });
  const addNamed = (key: "skills" | "technologies" | "tools") => setCandidate({ ...candidate, [key]: [...candidate[key], { name: "", level: null }] });
  const addLanguage = () => setCandidate({ ...candidate, languages: [...candidate.languages, { name: "", level: null }] });
  const addCertification = () => setCandidate({ ...candidate, certifications: [...candidate.certifications, { name: "", issuer: "", issue_date: null, expiration_date: null, credential_id: null, credential_url: null }] });
  const addProject = () => setCandidate({ ...candidate, projects: [...candidate.projects, { name: "", description: "", start_date: null, end_date: null, technologies: [], url: null }] });

  return <Card><div className="mb-5"><h2 className="text-xl font-bold">Seu currículo</h2><p className="mt-1 text-sm text-slate-500">Preencha apenas informações verdadeiras. O Resume AI nunca adicionará experiência que você não possui.</p></div>
    <Section title="Dados pessoais" defaultOpen><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome completo" placeholder="Jane Doe" value={candidate.personal_info.full_name} onChange={v => update(["personal_info", "full_name"], v)} /><Field label="E-mail" type="email" placeholder="jane@email.com" value={candidate.contact_info.email} onChange={v => update(["contact_info", "email"], v)} /><Field label="Telefone" placeholder="+55 41 99999-9999" value={candidate.contact_info.phone} onChange={v => update(["contact_info", "phone"], v)} /><Field label="Cidade" placeholder="Curitiba" value={candidate.personal_info.city} onChange={v => update(["personal_info", "city"], v)} /><Field label="Estado" placeholder="PR" value={candidate.personal_info.state} onChange={v => update(["personal_info", "state"], v)} /><Field label="País" placeholder="Brasil" value={candidate.personal_info.country} onChange={v => update(["personal_info", "country"], v)} /><Field label="LinkedIn" placeholder="linkedin.com/in/seu-nome" value={candidate.professional_links.linkedin ?? ""} onChange={v => update(["professional_links", "linkedin"], v)} /><Field label="GitHub" placeholder="github.com/seu-nome" value={candidate.professional_links.github ?? ""} onChange={v => update(["professional_links", "github"], v)} /></div></Section>
    <Section title="Experiência profissional"><div className="space-y-4">{candidate.experiences.map((experience, index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="mb-4 flex justify-between"><b>Experiência {index + 1}</b><button type="button" onClick={() => setCandidate({ ...candidate, experiences: candidate.experiences.filter((_, i) => i !== index) })} className="text-sm text-rose-500">Remover</button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Cargo" placeholder="Backend Developer" value={experience.role} onChange={v => update(["experiences", String(index), "role"], v)} /><Field label="Empresa" placeholder="Example Corp" value={experience.company} onChange={v => update(["experiences", String(index), "company"], v)} /><Field label="Início" type="date" value={experience.start_date} onChange={v => update(["experiences", String(index), "start_date"], v)} /><Field label="Fim" type="date" value={experience.end_date ?? ""} onChange={v => update(["experiences", String(index), "end_date"], v)} /></div><div className="mt-4"><TextArea label="Responsabilidades" placeholder="Desenvolvi APIs REST..." value={experience.activities.map(item => item.description).join("\n")} onChange={v => update(["experiences", String(index), "activities", "0", "description"], v)} /></div><div className="mt-4"><TextArea label="Resultados / conquistas" placeholder="Reduzi tempo de atendimento..." value={experience.achievements.map(item => item.description).join("\n")} onChange={v => update(["experiences", String(index), "achievements", "0", "description"], v)} /></div></div>)}</div><button type="button" onClick={addExperience} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar experiência</button></Section>
    <Section title="Formação"><div className="space-y-4">{candidate.education.map((item, index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Curso" value={item.course} onChange={v => update(["education", String(index), "course"], v)} /><Field label="Instituição" value={item.institution} onChange={v => update(["education", String(index), "institution"], v)} /><label className="space-y-1.5 text-sm font-semibold text-slate-700">Status<select value={item.status} onChange={e => update(["education", String(index), "status"], e.target.value)} className="w-full rounded-xl border border-slate-200 px-3.5 py-3 font-normal"><option value="completed">completed</option><option value="in_progress">in_progress</option><option value="interrupted">interrupted</option></select></label></div></div>)}</div><button type="button" onClick={addEducation} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar formação</button></Section>
    <CollectionSection title="Competências" items={candidate.skills} levels={levels} onAdd={() => addNamed("skills")} onChange={(i, v) => update(["skills", String(i), "name"], v)} />
    <CollectionSection title="Tecnologias" items={candidate.technologies} levels={levels} onAdd={() => addNamed("technologies")} onChange={(i, v) => update(["technologies", String(i), "name"], v)} />
    <CollectionSection title="Ferramentas" items={candidate.tools} levels={levels} onAdd={() => addNamed("tools")} onChange={(i, v) => update(["tools", String(i), "name"], v)} />
    <Section title="Idiomas"><div className="space-y-3">{candidate.languages.map((item, i) => <div key={i} className="flex gap-3"><Field label="Idioma" value={item.name} onChange={v => update(["languages", String(i), "name"], v)} /><select value={item.level ?? ""} onChange={e => update(["languages", String(i), "level"], e.target.value)} className="mt-6 rounded-xl border border-slate-200 px-3 text-sm"><option value="">Nível</option>{languageLevels.map(level => <option key={level}>{level}</option>)}</select></div>)}</div><button type="button" onClick={addLanguage} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar idioma</button></Section>
    <Section title="Certificações"><div className="space-y-3">{candidate.certifications.map((item, i) => <div key={i} className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-2"><Field label="Nome" value={item.name} onChange={v => update(["certifications", String(i), "name"], v)} /><Field label="Emissor" value={item.issuer} onChange={v => update(["certifications", String(i), "issuer"], v)} /></div>)}</div><button type="button" onClick={addCertification} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar certificação</button></Section>
    <Section title="Projetos"><div className="space-y-3">{candidate.projects.map((item, i) => <div key={i} className="space-y-3 rounded-xl border border-slate-200 p-4"><Field label="Nome do projeto" value={item.name} onChange={v => update(["projects", String(i), "name"], v)} /><TextArea label="Descrição" value={item.description} onChange={v => update(["projects", String(i), "description"], v)} /></div>)}</div><button type="button" onClick={addProject} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar projeto</button></Section>
  </Card>;
}

function CollectionSection({ title, items, levels, onAdd, onChange }: { title: string; items: { name: string; level: ProficiencyLevel | null }[]; levels: ProficiencyLevel[]; onAdd: () => void; onChange: (index: number, value: string) => void }) { return <Section title={title}><div className="space-y-3">{items.map((item, i) => <div key={i} className="flex items-end gap-3"><div className="flex-1"><Field label={title.slice(0, -1)} value={item.name} onChange={v => onChange(i, v)} /></div><span className="mb-3 rounded-lg bg-slate-50 px-2 py-1 text-xs text-slate-500">{item.level ?? levels[0]}</span></div>)}</div><button type="button" onClick={onAdd} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar {title.toLowerCase().slice(0, -1)}</button></Section>; }
