"use client";

import { Candidate, EducationStatus, LanguageLevel, ProficiencyLevel } from "../lib/types";
import { Card, Field, Section, TextArea } from "./ui";

const proficiencyLevels: ProficiencyLevel[] = ["basic", "intermediate", "advanced", "expert"];
const languageLevels: LanguageLevel[] = ["basic", "intermediate", "advanced", "fluent", "native"];
const educationStatuses: EducationStatus[] = ["in_progress", "completed", "interrupted"];

const labels: Record<string, string> = {
  basic: "Básico", intermediate: "Intermediário", advanced: "Avançado", expert: "Expert",
  fluent: "Fluente", native: "Nativo", in_progress: "Em andamento", completed: "Concluído", interrupted: "Interrompido",
};

export function CandidateForm({ candidate, setCandidate, onClear }: { candidate: Candidate; setCandidate: (candidate: Candidate) => void; onClear: () => void }) {
  const updatePersonal = (key: keyof Candidate["personal_info"], value: string) => setCandidate({ ...candidate, personal_info: { ...candidate.personal_info, [key]: value } });
  const updateContact = (key: keyof Candidate["contact_info"], value: string) => setCandidate({ ...candidate, contact_info: { ...candidate.contact_info, [key]: value } });
  const updateLinks = (key: keyof Candidate["professional_links"], value: string) => setCandidate({ ...candidate, professional_links: { ...candidate.professional_links, [key]: value || null } });
  const updateExperience = (index: number, key: "company" | "role" | "start_date" | "end_date", value: string | null) => setCandidate({ ...candidate, experiences: candidate.experiences.map((item, i) => i === index ? { ...item, [key]: value } : item) });
  const updateEducation = (index: number, key: "institution" | "course" | "status" | "start_date" | "end_date", value: string | null) => setCandidate({ ...candidate, education: candidate.education.map((item, i) => i === index ? { ...item, [key]: value } : item) });
  const updateNamed = (key: "skills" | "technologies" | "tools", index: number, field: "name" | "level", value: string | null) => setCandidate({ ...candidate, [key]: candidate[key].map((item, i) => i === index ? { ...item, [field]: value } : item) });
  const updateLanguage = (index: number, field: "name" | "level", value: string | null) => setCandidate({ ...candidate, languages: candidate.languages.map((item, i) => i === index ? { ...item, [field]: value } : item) });
  const updateCertification = (index: number, field: keyof Candidate["certifications"][number], value: string | null) => setCandidate({ ...candidate, certifications: candidate.certifications.map((item, i) => i === index ? { ...item, [field]: value } : item) });
  const updateProject = (index: number, field: keyof Candidate["projects"][number], value: string | null) => setCandidate({ ...candidate, projects: candidate.projects.map((item, i) => i === index ? { ...item, [field]: value } : item) });
  const updateProjectTechnologies = (index: number, technologies: string[]) => setCandidate({ ...candidate, projects: candidate.projects.map((item, i) => i === index ? { ...item, technologies } : item) });
  const updateExperienceList = (index: number, field: "activities" | "achievements", values: { description: string }[]) => setCandidate({ ...candidate, experiences: candidate.experiences.map((item, i) => i === index ? { ...item, [field]: values } : item) });

  const addExperience = () => setCandidate({ ...candidate, experiences: [...candidate.experiences, { company: "", role: "", start_date: "", end_date: null, activities: [], achievements: [] }] });
  const addEducation = () => setCandidate({ ...candidate, education: [...candidate.education, { institution: "", course: "", status: "", start_date: null, end_date: null }] });
  const addNamed = (key: "skills" | "technologies" | "tools") => setCandidate({ ...candidate, [key]: [...candidate[key], { name: "", level: null }] });
  const addLanguage = () => setCandidate({ ...candidate, languages: [...candidate.languages, { name: "", level: null }] });
  const addCertification = () => setCandidate({ ...candidate, certifications: [...candidate.certifications, { name: "", issuer: "", issue_date: null, expiration_date: null, credential_id: null, credential_url: null }] });
  const addProject = () => setCandidate({ ...candidate, projects: [...candidate.projects, { name: "", description: "", start_date: null, end_date: null, technologies: [], url: null }] });

  return <Card><div className="mb-5"><h2 className="text-xl font-bold">Seu currículo</h2><p className="mt-1 text-sm text-slate-500">Preencha apenas informações verdadeiras. O Resume AI nunca adicionará experiência que você não possui.</p></div>
    <Section title="Dados pessoais" defaultOpen><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome completo" placeholder="Jane Doe" value={candidate.personal_info.full_name} onChange={v => updatePersonal("full_name", v)} /><Field label="E-mail" type="email" placeholder="jane@email.com" value={candidate.contact_info.email} onChange={v => updateContact("email", v)} /><Field label="Telefone" placeholder="+55 41 99999-9999" value={candidate.contact_info.phone} onChange={v => updateContact("phone", v)} /><Field label="Cidade" placeholder="Curitiba" value={candidate.personal_info.city} onChange={v => updatePersonal("city", v)} /><Field label="Estado" placeholder="PR" value={candidate.personal_info.state} onChange={v => updatePersonal("state", v)} /><Field label="País" placeholder="Brasil" value={candidate.personal_info.country} onChange={v => updatePersonal("country", v)} /><Field label="LinkedIn" placeholder="linkedin.com/in/seu-nome" value={candidate.professional_links.linkedin ?? ""} onChange={v => updateLinks("linkedin", v)} /><Field label="GitHub" placeholder="github.com/seu-nome" value={candidate.professional_links.github ?? ""} onChange={v => updateLinks("github", v)} /><Field label="Portfolio" placeholder="seuportfolio.com" value={candidate.professional_links.portfolio ?? ""} onChange={v => updateLinks("portfolio", v)} /></div></Section>
    <Section title="Experiência profissional"><div className="space-y-4">{candidate.experiences.map((experience, index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="mb-4 flex items-center justify-between"><b>Experiência {index + 1}</b><button type="button" onClick={() => setCandidate({ ...candidate, experiences: candidate.experiences.filter((_, i) => i !== index) })} className="text-sm text-rose-500">Remover</button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Cargo" placeholder="Backend Developer" value={experience.role} onChange={v => updateExperience(index, "role", v)} /><Field label="Empresa" placeholder="Example Corp" value={experience.company} onChange={v => updateExperience(index, "company", v)} /><Field label="Início" type="month" value={experience.start_date} onChange={v => updateExperience(index, "start_date", v)} /><Field label="Fim" type="month" value={experience.end_date ?? ""} disabled={experience.end_date === null} onChange={v => updateExperience(index, "end_date", v || null)} /></div><label className="mt-4 flex items-center gap-2 text-sm font-semibold text-slate-600"><input type="checkbox" checked={experience.end_date === null} onChange={e => updateExperience(index, "end_date", e.target.checked ? null : "")} /> Trabalho atual</label><ListEditor title="Responsabilidades" items={experience.activities} placeholder="Desenvolvi APIs REST..." onChange={values => updateExperienceList(index, "activities", values)} /><ListEditor title="Resultados / conquistas" items={experience.achievements} placeholder="Reduzi tempo de atendimento..." onChange={values => updateExperienceList(index, "achievements", values)} /></div>)}</div><button type="button" onClick={addExperience} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar experiência</button></Section>
    <Section title="Formação"><div className="space-y-4">{candidate.education.map((item, index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex justify-between"><b>Formação {index + 1}</b><button type="button" onClick={() => setCandidate({ ...candidate, education: candidate.education.filter((_, i) => i !== index) })} className="text-sm text-rose-500">Remover</button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Curso" value={item.course} onChange={v => updateEducation(index, "course", v)} /><Field label="Instituição" value={item.institution} onChange={v => updateEducation(index, "institution", v)} /><Select label="Status" value={item.status} options={educationStatuses} onChange={v => updateEducation(index, "status", v)} /><Field label="Início" type="month" value={item.start_date ?? ""} onChange={v => updateEducation(index, "start_date", v || null)} /><Field label="Fim" type="month" value={item.end_date ?? ""} onChange={v => updateEducation(index, "end_date", v || null)} /></div></div>)}</div><button type="button" onClick={addEducation} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar formação</button></Section>
    <CollectionSection title="Competências" items={candidate.skills} levels={proficiencyLevels} onAdd={() => addNamed("skills")} onRemove={i => setCandidate({ ...candidate, skills: candidate.skills.filter((_, index) => index !== i) })} onChange={(i, f, v) => updateNamed("skills", i, f, v)} />
    <CollectionSection title="Tecnologias" items={candidate.technologies} levels={proficiencyLevels} onAdd={() => addNamed("technologies")} onRemove={i => setCandidate({ ...candidate, technologies: candidate.technologies.filter((_, index) => index !== i) })} onChange={(i, f, v) => updateNamed("technologies", i, f, v)} />
    <CollectionSection title="Ferramentas" items={candidate.tools} levels={proficiencyLevels} onAdd={() => addNamed("tools")} onRemove={i => setCandidate({ ...candidate, tools: candidate.tools.filter((_, index) => index !== i) })} onChange={(i, f, v) => updateNamed("tools", i, f, v)} />
    <Section title="Idiomas"><div className="space-y-3">{candidate.languages.map((item, i) => <div key={i} className="flex items-end gap-3 rounded-xl border border-slate-200 p-4"><div className="flex-1"><Field label={`Idioma ${i + 1}`} value={item.name} onChange={v => updateLanguage(i, "name", v)} /></div><Select label="Nível" value={item.level ?? ""} options={languageLevels} onChange={v => updateLanguage(i, "level", v || null)} /><button type="button" onClick={() => setCandidate({ ...candidate, languages: candidate.languages.filter((_, index) => index !== i) })} className="mb-3 text-sm text-rose-500">Remover</button></div>)}</div><button type="button" onClick={addLanguage} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar idioma</button></Section>
    <Section title="Certificações"><div className="space-y-3">{candidate.certifications.map((item, i) => <div key={i} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex justify-between"><b>Certificação {i + 1}</b><button type="button" onClick={() => setCandidate({ ...candidate, certifications: candidate.certifications.filter((_, index) => index !== i) })} className="text-sm text-rose-500">Remover</button></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Nome" value={item.name} onChange={v => updateCertification(i, "name", v)} /><Field label="Emissor" value={item.issuer} onChange={v => updateCertification(i, "issuer", v)} /><Field label="Data de emissão" type="date" value={item.issue_date ?? ""} onChange={v => updateCertification(i, "issue_date", v || null)} /><Field label="Validade" type="date" value={item.expiration_date ?? ""} onChange={v => updateCertification(i, "expiration_date", v || null)} /><Field label="ID da credencial" value={item.credential_id ?? ""} onChange={v => updateCertification(i, "credential_id", v || null)} /><Field label="URL da credencial" value={item.credential_url ?? ""} onChange={v => updateCertification(i, "credential_url", v || null)} /></div></div>)}</div><button type="button" onClick={addCertification} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar certificação</button></Section>
    <Section title="Projetos"><div className="space-y-3">{candidate.projects.map((item, i) => <div key={i} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex justify-between"><b>Projeto {i + 1}</b><button type="button" onClick={() => setCandidate({ ...candidate, projects: candidate.projects.filter((_, index) => index !== i) })} className="text-sm text-rose-500">Remover</button></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Nome" value={item.name} onChange={v => updateProject(i, "name", v)} /><Field label="URL" value={item.url ?? ""} onChange={v => updateProject(i, "url", v || null)} /><Field label="Início" type="month" value={item.start_date ?? ""} onChange={v => updateProject(i, "start_date", v || null)} /><Field label="Fim" type="month" value={item.end_date ?? ""} onChange={v => updateProject(i, "end_date", v || null)} /></div><TextArea label="Descrição" value={item.description} onChange={v => updateProject(i, "description", v)} /><ListEditor title="Tecnologias do projeto" items={item.technologies.map(description => ({ description }))} placeholder="Python" onChange={values => updateProjectTechnologies(i, values.map(value => value.description))} /></div>)}</div><button type="button" onClick={addProject} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar projeto</button></Section>
    <div className="mt-5 flex flex-col gap-2 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-400">Seu currículo fica salvo neste navegador.</p><button type="button" onClick={onClear} className="self-start rounded-lg px-2 py-1 text-xs font-semibold text-slate-500 transition hover:bg-slate-100 hover:text-slate-700">Limpar currículo</button></div></Card>;
}

function ListEditor({ title, items, placeholder, onChange }: { title: string; items: { description: string }[]; placeholder: string; onChange: (items: { description: string }[]) => void }) { return <div className="mt-4"><div className="mb-2 text-sm font-semibold text-slate-700">{title}</div><div className="space-y-2">{items.map((item, index) => <div key={index} className="flex gap-2"><input value={item.description} placeholder={placeholder} onChange={e => onChange(items.map((value, i) => i === index ? { description: e.target.value } : value))} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100" /><button type="button" onClick={() => onChange(items.filter((_, i) => i !== index))} className="px-2 text-sm text-rose-500">×</button></div>)}</div><button type="button" onClick={() => onChange([...items, { description: "" }])} className="mt-2 text-sm font-bold text-indigo-600">+ Adicionar {title.toLowerCase().replace("/", "ou").replace("resultados ", "conquista")}</button></div>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="block min-w-36 space-y-1.5 text-sm font-semibold text-slate-700">{label}<select value={value} onChange={e => onChange(e.target.value || "")} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-normal"><option value="">Selecione</option>{options.map(option => <option key={option} value={option}>{labels[option] ?? option}</option>)}</select></label>; }
function CollectionSection({ title, items, levels, onAdd, onRemove, onChange }: { title: string; items: { name: string; level: ProficiencyLevel | null }[]; levels: ProficiencyLevel[]; onAdd: () => void; onRemove: (index: number) => void; onChange: (index: number, field: "name" | "level", value: string | null) => void }) { return <Section title={title}><div className="space-y-3">{items.map((item, i) => <div key={i} className="flex items-end gap-3 rounded-xl border border-slate-200 p-4"><div className="flex-1"><Field label={`${title} ${i + 1}`} value={item.name} onChange={v => onChange(i, "name", v)} /></div><Select label="Nível" value={item.level ?? ""} options={levels} onChange={v => onChange(i, "level", v || null)} /><button type="button" onClick={() => onRemove(i)} className="mb-3 text-sm text-rose-500">Remover</button></div>)}</div><button type="button" onClick={onAdd} className="mt-4 text-sm font-bold text-indigo-600">+ Adicionar {title.toLowerCase().replace("competências", "competência").replace("tecnologias", "tecnologia").replace("ferramentas", "ferramenta")}</button></Section>; }
