"use client";

import { ReactNode } from "react";

export function AppHeader() { return <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-4 lg:px-10"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-lg font-bold text-white">R</div><span className="text-lg font-bold tracking-tight">Resume <span className="text-indigo-600">AI</span></span></div><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700">ATS Resume Analyzer</span></div></header>; }

export function StepIndicator({ step }: { step: number }) { return <div className="flex items-center gap-2 text-sm"><span className="flex items-center gap-2 font-semibold text-indigo-700"><b className="grid h-7 w-7 place-items-center rounded-full bg-indigo-600 text-white">1</b> Currículo</span><span className="h-px w-8 bg-slate-200"/><span className={`flex items-center gap-2 ${step >= 2 ? "font-semibold text-indigo-700" : "text-slate-400"}`}><b className={`grid h-7 w-7 place-items-center rounded-full ${step >= 2 ? "bg-indigo-600 text-white" : "bg-slate-100"}`}>2</b> Vaga</span><span className="h-px w-8 bg-slate-200"/><span className="flex items-center gap-2 text-slate-400"><b className="grid h-7 w-7 place-items-center rounded-full bg-slate-100">3</b> Resultado</span></div>; }

export function Field({ label, value, onChange, placeholder, type = "text", disabled = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string; disabled?: boolean }) { return <label className="block space-y-1.5"><span className="text-sm font-semibold text-slate-700">{label}</span><input disabled={disabled} type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm text-slate-800 shadow-sm transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100 disabled:bg-slate-100" /></label>; }
export function TextArea({ label, value, onChange, placeholder, className = "" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; className?: string }) { return <label className="block space-y-1.5"><span className="text-sm font-semibold text-slate-700">{label}</span><textarea value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className={`min-h-24 w-full resize-y rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm text-slate-800 shadow-sm transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100 ${className}`} /></label>; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-soft sm:p-7 ${className}`}>{children}</section>; }
export function Section({ title, children, defaultOpen = false }: { title: string; children: ReactNode; defaultOpen?: boolean }) { return <details open={defaultOpen} className="group border-b border-slate-100 py-4 last:border-0"><summary className="flex cursor-pointer list-none items-center justify-between text-base font-bold text-slate-800 [&::-webkit-details-marker]:hidden"><span>{title}</span><span className="text-xl font-normal text-slate-400 transition group-open:rotate-45">+</span></summary><div className="pt-5">{children}</div></details>; }
export function PrimaryButton({ children, onClick, disabled = false }: { children: ReactNode; onClick?: () => void; disabled?: boolean }) { return <button disabled={disabled} onClick={onClick} className="w-full rounded-xl bg-indigo-600 px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">{children}</button>; }
